name: Fetch Bazaar Data

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Download previous data artifact
        uses: actions/download-artifact@v2
        with:
          name: bazaar-data
          path: data/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: |
          python getData.py

      - name: List files in data folder
        run: |
          ls -al data

      - name: Upload new data artifact
        uses: actions/upload-artifact@v2
        with:
          name: bazaar-data
          path: data/
